In [1]:
import numpy as np
from keras import models
import time
import cv2

2024-08-31 23:04:29.168719: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
def onehot_to_classname(one_hot):
    max_idx = 0
    max_val = 0
    for (idx, val) in enumerate(one_hot[0]):
        if val > max_val:
            max_val = val
            max_idx = idx

    return ["scisor", "rock", "paper"][max_idx]


In [3]:
name='MobileNet_fineturn_20240903_1653.h5'
model = models.load_model(name)
print("load ",name)

# 選擇第攝影機
cap = cv2.VideoCapture(0)

2024-08-31 23:04:34.392584: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


load  MobileNet_fineturn_20240831_2302.h5


In [4]:
while(True):
    # 從攝影機擷取一張影像
    ret, frame = cap.read()
    
    # 模型預估
    frame_resize = cv2.resize(frame, (224, 224), interpolation=cv2.INTER_AREA)
    input_data=frame_resize[np.newaxis,:,:,:]
    start = time.time()
    prediction=model.predict(input_data) 
    print(prediction)
    end = time.time()
    accumulate_time = (end - start)
    FPS = 1/accumulate_time
    FPS = round(FPS,2)
    detected = onehot_to_classname(prediction)
    print(detected)
    # 顯示圖片
    cv2.putText(frame, str(FPS), (540, 40), cv2.FONT_HERSHEY_SIMPLEX,1, (0, 0, 255), 1, cv2.LINE_AA)
    cv2.putText(frame, detected, (10, 40), cv2.FONT_HERSHEY_SIMPLEX,1, (255, 0, 0), 1, cv2.LINE_AA)
    cv2.imshow('frame', frame)
    
    # 若按下 q 鍵則離開迴圈
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# 釋放攝影機
cap.release()

# 關閉所有 OpenCV 視窗
cv2.destroyAllWindows()


1/1 [==============================] - 1s 551ms/step
[[0.03303991 0.9046873  0.06227277]]
rock


qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/hui0415/anaconda3/envs/MNIST/lib/python3.10/site-packages/cv2/qt/plugins"
QObject::moveToThread: Current thread (0x91b9990) is not the object's thread (0x8c7e0a0).
Cannot move to target thread (0x91b9990)

QObject::moveToThread: Current thread (0x91b9990) is not the object's thread (0x8c7e0a0).
Cannot move to target thread (0x91b9990)

QObject::moveToThread: Current thread (0x91b9990) is not the object's thread (0x8c7e0a0).
Cannot move to target thread (0x91b9990)

QObject::moveToThread: Current thread (0x91b9990) is not the object's thread (0x8c7e0a0).
Cannot move to target thread (0x91b9990)

QObject::moveToThread: Current thread (0x91b9990) is not the object's thread (0x8c7e0a0).
Cannot move to target thread (0x91b9990)

QObject::moveToThread: Current thread (0x91b9990) is not the object's thread (0x8c7e0a0).
Cannot move to target thread (0x91b9990)

QObject::moveToThread: Current thread (0x91b9990) is not the 

1/1 [==============================] - 0s 40ms/step


QObject::moveToThread: Current thread (0x91b9990) is not the object's thread (0x8c7e0a0).
Cannot move to target thread (0x91b9990)

QObject::moveToThread: Current thread (0x91b9990) is not the object's thread (0x8c7e0a0).
Cannot move to target thread (0x91b9990)



[[0.03259085 0.90625095 0.06115811]]
rock
1/1 [==============================] - 0s 23ms/step
[[0.0352706  0.8997937  0.06493572]]
rock
1/1 [==============================] - 0s 34ms/step
[[0.03788682 0.8954935  0.06661962]]
rock
1/1 [==============================] - 0s 37ms/step
[[0.03459987 0.90173167 0.06366841]]
rock
1/1 [==============================] - 0s 44ms/step
[[0.18762226 0.39876366 0.41361412]]
paper
1/1 [==============================] - 0s 75ms/step
[[0.1696394  0.43256578 0.39779475]]
rock
1/1 [==============================] - 0s 64ms/step
[[0.18578228 0.511196   0.30302167]]
rock
1/1 [==============================] - 0s 77ms/step
[[0.10605794 0.44805893 0.44588304]]
rock
1/1 [==============================] - 0s 61ms/step
[[0.11973213 0.39415503 0.48611283]]
paper
1/1 [==============================] - 0s 41ms/step
[[0.12813713 0.3041646  0.56769836]]
paper
1/1 [==============================] - 0s 61ms/step
[[0.27402583 0.23178367 0.4941905 ]]
paper
1/1 [=========